### ISSUE TITLE
Accessing the website using localhost:3479 throws error

### ISSUE THREAD

**Issue by seunex17** [firtadokei/codeigniter-vitejs#11]
After running npm run dev and create a server via htpp://localhost:3479 throws error 404 page

![image](https://user-images.githubusercontent.com/38796424/179789795-ab1bb209-f892-4304-aeaa-a555321ffb6f.png)

**Comment by seunex17** [comment]
After creating a new CI4 project I then install your package and use `php spark vite:init --framework svelte` this then install svelte and I run npm run dev and throw above error am I missing something?

**Comment by jaguarch** [comment]
Yup, you didn't run `php spark serve` then you should open `http://localhost:8080` instead.

**Comment by seunex17** [comment]
The doc set run npm run dev. Well will take a look again. Well I am not seeing App.svelte in my public folder. 

Will appreciate an example project to fully take a look at this.

**Comment by jaguarch** [comment]
Let me make it clear
- create ci4 project `composer create-project...`
- install the package `composer require mihatori/codeignitervite`
- initialize it `php spark vite:init --framework svelte`, this command will create a resources folder in your rootpath, you will find `App.svelte` file there.
- run `npm install` then `npm run dev`, this will serve vite on port 3479 but you got nothing to do with,
- run `php spark serve` now open `http://localhost:8080` and everything should work fine.

About the example project, is almost ready it's just a matter of day or two

**Comment by firtadokei** [comment]
After following the installation instructions, run `php spark serve` and access your project through codeigniter development server wich is by default `http://localhost:8080`

 `php spark vite:init` will generate a resources folder and you should find your App.svelete there

**Comment by PwrSrg** [comment]
I had the **exact same issue**, and finally just gave up.

You **_really_** need to update your documentation to make it _clear_ that you actually need to be running TWO terminals - one running Vite, and _second_ one running CodeIgniter **at the same time**.

That would have saved me a ton of time and frustration.

**Comment by firtadokei** [comment]
Hi @PwrSrg
You're right, i'm sorry about that 
i'm currently working on starter app for vue and svelte, but I would appreciate it if someone could help me with the documentation

**Comment by firtadokei** [comment]
#13

**Comment by firtadokei** [comment]
@seunex17
check this out https://github.com/firtadokei/ci-svelte-appstarter

**Comment by seunex17** [comment]
@firtadokei  perfect a very big thank you

**Comment by PwrSrg** [comment]
NICE! 🤩

**Comment by firtadokei** [comment]
@Gildedter nope, spark is not required
