### ISSUE TITLE
SvelteKit support

### ISSUE THREAD

**Issue by seunex17** [firtadokei/codeigniter-vitejs#17]
Hello, I really love the starter template, which seems to be a very good kick start to the repo.

Please, I don't know if it's possible to support SvelteKit and we use CodeIgniter as the server side.

**Comment by jaguarch** [comment]
Working on it, i'll let you know as soon as possible

**Comment by seunex17** [comment]
> Working on it, i'll let you know as soon as possible

Thanks Man 😊

**Comment by firtadokei** [comment]
@jaguarch SvelteKit  isn't stable yet, expect bugs

**Comment by PwrSrg** [comment]
I am extremely interested in this as well!

**Comment by jaguarch** [comment]
@seunex17  @PwrSrg

https://github.com/firtadokei/codeigniter-vitejs/tree/v2

Let me know if it works fine

**Comment by seunex17** [comment]
@jaguarch  Will let you know ASAP 😃

**Comment by seunex17** [comment]
@jaguarch It looks great when you start the server from the base url (http://localhost:8080). After the landing page, I then navigate to the about page, which works really well now. I try to reload the page when at the about page or visit the about page url directly (http://localhost:8080/about). While loading the page, it first displays the CodeIgniter default page, followed by a blank page, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/38796424/182451755-79f92bac-4f6b-4774-89e5-927f98be16a7.png)


I think more work here is in the .htaccess file we need to send every request to index.php file.

**Comment by seunex17** [comment]
Going through the package src file, I notice that the Codeigniter4 Vite has a default home page route defined, which points to the Codeigniter default homepage. I delete this file and replace it with a very simple blank index page that has a div element with an id=app.

It seems to be looking good after taking the above process.

**Comment by PwrSrg** [comment]
**NICE Catch!** 👍🏼

**Comment by seunex17** [comment]
This is really looking good. The load() function is fantastic! Loading data from Codeingiter is just perfect, man!

**Comment by jaguarch** [comment]
@seunex17 
Glad to hear that, i'm always ready to help if you have any other suggestion.
