### ISSUE TITLE
`__construct expects a valid directory.` error while running command `./spark vite:init`

### ISSUE THREAD

**Issue by baharsah** [firtadokei/codeigniter-vitejs#24]
CodeIgniter version: 
Package version: 4.2.10

**Describe the bug**
`__construct expects a valid directory.` error while running command `./spark vite:init` ([CodeIgniter\Files\Exceptions\FileException])

**Expected behavior**
-

**Additional context**
![image](https://user-images.githubusercontent.com/69349170/200334934-2acabf35-ab93-4afe-b45f-3c1e38b6e31f.png)

**Comment by scastiello** [comment]
I have the same problem too.
